### ISSUE TITLE
Search page: Text needs translated on French page

### ISSUE THREAD

**Issue by ndolter** [mmiron-HC/WST-RSAMS#102]
URL: https://hcdev.openplus.ca/fr/search/site
User Agent: Chrome
Language: French

Issue Description: There is English text on the French 'Recherche' page.  All text should contain the language of the page.

Steps to reproduce: Visual scanning

Expected results: All text should contain the correct language of the page.

![image](https://user-images.githubusercontent.com/68117281/136611711-4d4702f6-62be-4275-919b-f3fa8f0b2705.png)

**Comment by ndolter** [comment]
Checked in Firefox 93 and Edge 94. English text is still displayed. 
![image](https://user-images.githubusercontent.com/68117281/137194150-acc89937-5ea1-4e14-9ee4-f4d8f6043cdd.png)

**Comment by echouin** [comment]
Sent back to OP.

**Comment by echouin** [comment]
@ndolter OP confirms fixed.

**Comment by ndolter** [comment]
@echouin The label for the field is now entirely gone (both languages) and the field is skipped when tabbing through. 
![image](https://user-images.githubusercontent.com/68117281/137376887-97e23bcf-e103-4b66-ba3a-c581eda498a0.png)

**Comment by echouin** [comment]
@ndolter thank you, sending back to OP for fix :).

**Comment by echouin** [comment]
@ndolter OP confirms fixed. Additional notes from OP:

it is designed this way. The label was always supposed to be visually hidden, it was an update that made it visible. It is there in code for screen readers
﻿---﻿
<label class="sr-only control-label" for="edit-search-api-fulltext--2">Recherche</label>


﻿---

Tab issue is resolved.

**Comment by mmiron-HC** [comment]
@echouin while the label doesn't need to be visible. they should make the label visible as the "Search" button is not position right after the text field. There is a checkbox with long label in between the text field and button.
![image](https://user-images.githubusercontent.com/65728700/138923591-6f26c15a-1cd0-48fe-9537-d18b69693672.png)

**Comment by echouin** [comment]
@mmiron-HC back w/ OP

**Comment by echouin** [comment]
From OP: This will require a template change. This issue has morphed from its original ID'd error.

**Comment by echouin** [comment]
@ndolter & @mmiron-HC this is resolved on the current website. The UX thinking is (from OP): You have keywords followed by a prompt to include archived or not. I think this is logically how users would use that form, "I want to find 'xxxx', and I want to include archived recalls".

Here is the current look & feel on the live website (also verified tabbing order and it is working as intended):

![image](https://user-images.githubusercontent.com/88099454/148397934-9a0f8969-107e-46cb-9fd1-f106fe664fc4.png)

**Comment by ndolter** [comment]
This issue has now been resolved.
