### ISSUE TITLE
Subscribe: An end </div> is found, but there is no start <div> found.

### ISSUE THREAD

**Issue by XiuJuanXia** [mmiron-HC/WST-RSAMS#107]
URL: https://hcdev.openplus.ca/en/form/subscribe
User Agent: Chrome
Language: Both

Issue Description: In line 162, there is an end </div> found, but there was no start <div> found. View Page Source, search and there is 124 <div> and 125 </div>. 
![image](https://user-images.githubusercontent.com/88776404/136959486-27eafac8-8203-4695-9d74-287b52d2e1e9.png)

Steps to reproduce:

1. View page source
2. Copy page source to [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input)
3. Check

Expected results: Ensure there is no parsing error found.

**Comment by echouin** [comment]
@XiuJuanXia From OP: Fixed.

**Comment by XiuJuanXia** [comment]
Issue is fixed. Closing this issue.
