### ISSUE TITLE
Error when trying to access the Help section 

### ISSUE THREAD

**Issue by hydegeoff** [mmiron-HC/WST-RSAMS#137]
URL: https://rsams.dev.cloud.openplus.ca/en/documentation/recalls-and-safety-alerts-help-guide
User Agent: Chrome 99
Language:  English 

Issue Description: Error appears when trying to access the help section of the admin portal:
![Help section - error appears](https://user-images.githubusercontent.com/88147013/159742129-b1c2b504-d471-45e1-aa0b-0c017057b3c6.jpg)

Steps to reproduce: 
1. Login
2.  Select your username at the top Nav bar
3.  Select the Help link 
4.  Problem error appears near the top of the page.

Expected results:  
No system should appear

**Comment by echouin** [comment]
Hello @hydegeoff Can you please reference the latest Live version of the Help Guide: https://rsams.prod.cloud.openplus.ca/en/documentation/recalls-and-safety-alerts-help-guide

The one in the link is from the Dev.
Thank you,
Eric

**Comment by mmiron-HC** [comment]
@echouin this is a valid test. We are trying to access the help page from the admin content. We do not have access to the Admin side on prod.

**Comment by echouin** [comment]
@mmiron-HC you do have access on prod. website. Please use your same login credentials.

**Comment by echouin** [comment]
I'm not sure I understand this one. I would need some clarification?

**Comment by mmiron-HC** [comment]
@echouin follow the steps to reproduce in issue description above.

**Comment by hydegeoff** [comment]
You may need similar credentials to my user account.  This error appear immediately entering the Help section.  I think this error also causes issues with the icons as well.  Please take a look at my screenshot below:
![image](https://user-images.githubusercontent.com/88147013/159957312-0c638b4c-d812-4b8f-ad2c-ecb946612f20.png)

**Comment by echouin** [comment]
Hi, I reset my credentials.

This issue does not exist on the LIVE Version of the website:
![image](https://user-images.githubusercontent.com/88099454/159978510-9466782b-8aa6-470e-a7b5-2bcdd84f08c2.png)

![image](https://user-images.githubusercontent.com/88099454/159978547-4f382755-d0e9-4a15-ad4c-a0179a88c868.png)

**Comment by hydegeoff** [comment]
The issue seems to fixed in PROD strictly based on screenshots above.  This has not been been verified in PROD.

**Comment by hydegeoff** [comment]
This issue has been fixed in DEV
