### ISSUE TITLE
Help - some icons are not displaying properly

### ISSUE THREAD

**Issue by hydegeoff** [mmiron-HC/WST-RSAMS#146]
URL: https://rsams.dev.cloud.openplus.ca/en/documentation/getting-started
User Agent: Chrome 
Language:  EN/FR pages

Issue Description:
The icon shown in the screenshot below are not appearing correctly.  I have seen a similar issue on other help pages.

Steps to reproduce:

1. Login 
2. Go to help section 
3. Problem: on that introductory page is where the issue occurs
![Icons are not displaying properly](https://user-images.githubusercontent.com/88147013/161098595-668ee992-5e31-4dfa-a816-86246b0dc3e5.jpg)

Expected results:
All icons should appear correctly.

**Comment by echouin** [comment]
@hydegeoff that's on the Dev, so no need to fix.

**Comment by hydegeoff** [comment]
Since this issue only exists in DEV this issue will be closed

**Comment by hydegeoff** [comment]
Actually I need to see a screenshot of production before I am allowed to close the issue.

**Comment by echouin** [comment]
@hydegeoff 
FR: 
![image](https://user-images.githubusercontent.com/88099454/161294403-216b5d7b-5cc8-4232-aaf7-653743596e0b.png)
EN:
![image](https://user-images.githubusercontent.com/88099454/161294449-b1044041-7b16-4bf8-a09d-1003bb8596ca.png)

**Comment by hydegeoff** [comment]
Closed as per PROD screenshots provided
