### ISSUE TITLE
Login page – Missing Footer links when reflowed to phone size screen 

### ISSUE THREAD

**Issue by hydegeoff** [mmiron-HC/WST-RSAMS#23]
Problem:
If viewing the page on mobile phone device or shrinking the browser window to its smallest width the nine links and picture of the Parliament Building in the background is missing.

Expected Result:
Add 9 links and background image to the small size version of the footer as shown the TBS Guidelines: https://design.canada.ca/common-design-patterns/site-footer.html

URL: https://hcdev.openplus.ca/en/user/login
User Agent:  Chrome (Version 92.0.4515.107 (Official Build) (64-bit)); Firefox (90.0.2 (64-bit));
Also found issue on Samsung S10 phone/Chrome 
Language: EN and FR

The screenshot below is providing a view chrome's emulator's view:

Steps to reproduce: 
1.	In Chrome / laptop, Enter login info (hcdev/hc) into pop-up screen to access environment
2.	View the login page as shown in screen shot.
3.	Shrink window to it’s smallest width or access it on a cellphone.
4.	Problem occurs here: The footer no longer has the nine links and picture of the Parliament Building in the background.

![Login - Missing 9 links in the footer when Reflowed](https://user-images.githubusercontent.com/88147013/127704337-1eb6f5e9-c7e3-404e-859b-f661abf2b49c.JPG)

**Comment by qanitah** [comment]
This is also for iPhone 12 for all pages (Home, Dashboard, Edit Profile etc). 
Safari with iOS 14.7.1

![image](https://user-images.githubusercontent.com/14280062/128193663-9bb5c483-56c3-4860-8035-88ef2d50ade8.png)

**Comment by mmiron-HC** [comment]
Note that the footer appears when the orientation is landscape. 
![image](https://user-images.githubusercontent.com/65728700/128871660-e44d2cc1-60d0-4a47-bee1-9ef4df195f39.png)

**Comment by ndolter** [comment]
Tested on the iphone 11, as well as, testing in responsive design mode (Firefox: Ctl-Shift-M) and the English page now has the links in the footer, however, the French page is sill missing them.

**Comment by echouin** [comment]
@ndolter This item was fixed. Suggest item be closed.

**Comment by qanitah** [comment]
Fixed
