### ISSUE TITLE
Header – Language toggle appears incorrectly on a small screen

### ISSUE THREAD

**Issue by hydegeoff** [mmiron-HC/WST-RSAMS#24]
![Login-Samsung S10-language toggle appear incorrectly](https://user-images.githubusercontent.com/88147013/127724321-b05653bf-df74-4fa7-b00e-198b8adb5e69.jpg)
**Problem:**
The header template should display the language toggle as EN/FR when viewed on small screen or window.  It should not be on its own line.  

**Steps to reproduce:** 
1.	In Chrome / laptop, Enter login info (hcdev/hc) into pop-up screen to access environment
2.	View the login page as shown in screen shot 
3.	Shrink window to it’s smallest width or access it on a cellphone
4.	Problem occurs here: the header toggle button should be displayed as EN / FR instead of English and Francais 

**Expected Result** 
The language toggle should appear as EN or FR directly beside the government of Canada logo, in accordance with TBS guidelines 

**Impacts:** 
It is assumed that it impacts all pages on the site.

URL: https://hcdev.openplus.ca/en/user/login
User Agent:  Chrome (Version 92.0.4515.107 (Official Build) (64-bit)); Firefox (90.0.2 (64-bit));
                     Also Tested on Samsung S10 phone in Chrome browser
Language: EN and FR

**Comment by davidgotlieb** [comment]
﻿Updated our page template to match new 9.1 drupalwxt template

**Comment by ndolter** [comment]
Validated in both French and English that the smaller viewport (Tested in responsive design mode) now has EN and FR.
