### ISSUE TITLE
Edit profile: "Cancel account" button next to Save button instead of "Cancel"

### ISSUE THREAD

**Issue by qanitah** [mmiron-HC/WST-RSAMS#47]
URL: https://hcdev.openplus.ca/en/user/203/edit
User Agent: Chrome, Firefox
Language: both

Issue Description: Cancel account button at the end of the form is right after Save button. Usually, Save and Cancel (form) are adjacent to each other. But Cancel account seems to be out of place. This is a big action and user can mistakenly click on it. 

Expected results: Suggestion is to put Cancel account on a different location on it's own so the user does not confuse with a regular Cancel button (which is displayed as a simple text link right after it).

![image](https://user-images.githubusercontent.com/14280062/128714957-2abb9619-793b-48cd-a76d-efb95455b524.png)

**Comment by echouin** [comment]
This was fixed by ﻿OP in the final build.
﻿Departmental Admin view (editing an account profile):

![image](https://user-images.githubusercontent.com/88099454/148259385-1c719155-aeb9-439d-8614-4dbd51073f56.png)

**Comment by hydegeoff** [comment]
This issue can be closed
