### ISSUE TITLE
Footer: hidden headings/text do not match the Canada.ca template

### ISSUE THREAD

**Issue by mmiron-HC** [mmiron-HC/WST-RSAMS#60]
URL: throughout the app
User Agent: Chrome
Language: Both

**Issue Description:** Hidden headings are incorrect. they should match the Canada.ca template
improper headings, 

**Steps to reproduce:**

- View page in chrome, 
- Run WAVE and turn styles off
 ![image](https://user-images.githubusercontent.com/65728700/129060160-bfdad8d5-5e19-40df-8684-db23e3687083.png)
view footer

**Expected results:**
The hidden headings should match the canada.ca footer structure
![image](https://user-images.githubusercontent.com/65728700/129060708-1c14c352-5a11-4b24-913c-b96aeb8b1907.png)
![image](https://user-images.githubusercontent.com/65728700/129061263-2cadcf0e-f998-49a1-9edf-e5889b573fbe.png)

**Comment by ndolter** [comment]
Validated in both French and English that all the required changes listed above have been corrected.
