### ISSUE TITLE
Header: hidden Search label is incorrect

### ISSUE THREAD

**Issue by mmiron-HC** [mmiron-HC/WST-RSAMS#62]
URL: all pages
User Agent: Chrome
Language: En/Fr

**Issue Description:**
Hidden Search label is incorrect. does not match Canada.ca template

**Steps to reproduce:**
View page with styles turned off (Run WAVE and ensure styles are turned off)
view page headings compare to Canada.ca pages
![image](https://user-images.githubusercontent.com/65728700/129063994-694101a2-b0e9-4991-abc3-cff11821c52c.png)

**Expected results:**
This should match the canada.ca template "Search" in EN and "Recherche" in FR 
![image](https://user-images.githubusercontent.com/65728700/129064073-f0a04722-a5e7-46c1-83bf-cc82ddb97b06.png)
![image](https://user-images.githubusercontent.com/65728700/129064134-5acc6f2d-2e8d-43f3-9558-dfcc9fb51e58.png)

**Comment by davidgotlieb** [comment]
changed block title and added translation to match canada.ca

**Comment by ndolter** [comment]
The following issues still exist (https://hcdev.openplus.ca/en):
1. French & English pages: The 'Find'/'Trouver' button should be 'Search'/'Recherche' to match that of the Canada.ca template
2. French & English pages: The tooltip on the 'Find/Trouver' button is not required as it is redundant

![image](https://user-images.githubusercontent.com/68117281/131685787-e2ba623b-5645-4d48-b62c-86334b0a10a3.png)

**Comment by davidgotlieb** [comment]
This will be fixed on the next merge of fixes/theme into the current dev branch

**Comment by ndolter** [comment]
1. The 'Search' field still does not match to the Canada.ca theme page.  Also, please note that the text shouldn't be cut off in the Search field as is the case on the French page.  The language link is also not placed the same distance to the Search field as in the Canada.ca page
![image](https://user-images.githubusercontent.com/68117281/136255284-1100046a-598c-40d2-841a-f9fb112dde43.png)
![image](https://user-images.githubusercontent.com/68117281/136255337-cd522af7-db93-4b4c-810d-c1e86725092d.png)

2. The Search field on the Home page still has some discrepancies.  The tooltip is still displayed when it is not required and it is not identical to the label on the button which may cause confusion. 
![image](https://user-images.githubusercontent.com/68117281/136259208-8b948c40-48d6-4904-8f90-a1d23ea30544.png)

**Comment by echouin** [comment]
From OP: Fixed and will be part of my next merge request

**Comment by ndolter** [comment]
Validated the following in both languages:
1. The tooltip has been removed on the Search button
2. The field placement is now correctly aligned
3. The text in the field is no longer getting cut-off in French
