### ISSUE TITLE
Header: Hidden word Menu must be removed

### ISSUE THREAD

**Issue by mmiron-HC** [mmiron-HC/WST-RSAMS#65]
URL: all
User Agent: chrome
Language: fr/en

Issue Description: hidden word "Menu" must be removed it is remnants of the template and is not necessary.
Steps to reproduce:
view page with styles turned off (Run WAVE, styles = off) 
Scroll to where the breadcrumbs appear. 
![image](https://user-images.githubusercontent.com/65728700/129080764-5db0cff3-3dc6-4268-9243-8bd6ccc322cd.png)

Expected results:
Remove the heading Menu.

**Comment by ndolter** [comment]
Validated in both French and English that 'Menu' has been removed.
