### ISSUE TITLE
The Search tab: <h2> is skipped

### ISSUE THREAD

**Issue by XiuJuanXia** [mmiron-HC/WST-RSAMS#73]
URL: https://hcdev.openplus.ca/en/documentation/search-tab
User Agent: Chrome, JAWS
Language: Both

Issue Description: In this page, h2 is skipped. h1 is followed by h3.
![image](https://user-images.githubusercontent.com/88776404/129200667-9c6ed641-9389-46dc-b9bd-06960accb046.png)

Steps to reproduce: Inspect the element. And also listen to JAWS.

Expected results: Change the two h3s to h2 so that the headings are in a hierarchical layout.

**Comment by mmiron-HC** [comment]
@CraigClark you tagged this issue to 01_public_facing but we believe that this is part of the authenticated view. can you confirm?

**Comment by ndolter** [comment]
Validated in both languages that the heading structure is now correct.
![image](https://user-images.githubusercontent.com/68117281/135907130-1bb98ed4-e48d-422e-aac2-cf519325ac5e.png)
