### ISSUE TITLE
The Build: editing an alert/recall: image alternative text is not clear

### ISSUE THREAD

**Issue by XiuJuanXia** [mmiron-HC/WST-RSAMS#74]
URL: https://hcdev.openplus.ca/en/documentation/build-editing-alertrecall
User Agent: Chrome, JAWS
Language: English

Issue Description: The alternative text for the second image is not clear: "Screen capture showing the indicator on the top right that shows that the content is locked and available for editing." In the image, the "Lock and edit" button is available. The content is not locked. When the content is locked, "Unlocked" button is available. "Lock and edit" button disappears.

Also there is a grammar error in the alternative text for the first image: "Screen capture showing the indicator on the top right showing that the content is locked to another user."

Steps to reproduce: Activate a "Build" button beside an alert/recall where a "Lock and edit" button is available. Activate "Lock and edit" button to lock the content.

Expected results: Update the alternative text for the second image to something like this: "Screen capture showing the indicator on the top right that shows that the content is available to lock and edit."

Update the alternative text for the second image to "Screen capture showing the indicator on the top right that shows that the content is locked to another user."

**Comment by echouin** [comment]
﻿Fixed. Modified both image texts for clarify:
﻿Image # 1 (new text): ﻿﻿Top right notification that the content is locked to another user.

FR: no mod needed.

﻿Image # 2 ﻿(new text): ﻿Top right button is "lock and edit" which indicates that the content is unlocked and available for editing.

﻿FR (small mod - bolded): ﻿Capture d’écran montrant l’indicateur en haut à droite qui montre que le contenu est non-verrouillé et disponible pour modification.

**Comment by XiuJuanXia** [comment]
Confirmed this issue is fixed.
