### ISSUE TITLE
The Build: editing an alert/recall-Section 1: Underlined text is found

### ISSUE THREAD

**Issue by XiuJuanXia** [mmiron-HC/WST-RSAMS#78]
URL: https://hcdev.openplus.ca/en/documentation/section-1
User Agent: Chrome, JAWS
Language: English

Issue Description: Under "What to do (summary)", there is underlined text "one short sentence" that is not a hyperlink. According to [Canada.ca Content Style guide](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-2), use underlining for links only.
![image](https://user-images.githubusercontent.com/88776404/129227937-4498fd4f-e7b0-4a69-9094-60584b02597d.png)

Steps to reproduce: Navigating between links by tabbing, and focus will be never placed on the underlined text.

Expected results: Add hyperlink if it's a hyperlink. Otherwise, remove the underline.

**Comment by echouin** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/88099454/148239126-650c6379-1102-4532-b497-73e4c970779b.png)

**Comment by hydegeoff** [comment]
The original was fixed, but it was not fixed across the entire site.  Another issues occurs here:
https://rsams.dev.cloud.openplus.ca/en/documentation/creating-authlink-en-and-fr
impacts EN and FR pages 
Page location : 
(Top Nav) [Username] > Help > (right nav) The Build: editing an alert/recall > Creating an Authlink in EN and FR

![Underlined text issue](https://user-images.githubusercontent.com/88147013/159782286-3c59c9d1-3846-418a-8367-491ef0a9d4df.jpg)

**Comment by echouin** [comment]
@hydegeoff please use the final Help guide "live" version of the website: https://rsams.prod.cloud.openplus.ca/en/documentation/creating-authlink

**Comment by mmiron-HC** [comment]
@echouin we do not have access to the link you provided. We can and should only test the admin side in DEV.

**Comment by echouin** [comment]
@mmiron-HC you do have access on prod. website. Please use your same login credentials. Please ensure that you login first: https://rsams.prod.cloud.openplus.ca/en/user/login

**Comment by echouin** [comment]
Content was completely rewritten in EN and FR a few months ago to reflect the new instructions. This is no longer relevant.

![image](https://user-images.githubusercontent.com/88099454/159942826-1598843b-bac4-42b1-94ee-e33775e2f8e6.png)

![image](https://user-images.githubusercontent.com/88099454/159943022-498eb6fa-726f-4a1a-ad6d-f989ff1cb4cd.png)

**Comment by hydegeoff** [comment]
The issue seems to fixed in PROD strictly based on screenshots above. This has not been been verified in PROD.
