### ISSUE TITLE
Find Recalls: Unexpected behaviour occurring when clicking the Last button

### ISSUE THREAD

**Issue by ndolter** [mmiron-HC/WST-RSAMS#91]
URL: https://hcdev.openplus.ca/en
User Agent: Chrome 92.0, Firefox 91.0
Language: Both

Issue Description: When the user selects the 'Last' button at the bottom of the page, the numbered buttons are switched over to year numbers.

Steps to reproduce: Mouse and click

Expected results: The page numbers should not change
![image](https://user-images.githubusercontent.com/68117281/131535619-b917edce-6abd-48ff-97c4-8f31a016875d.png)

**Comment by davidgotlieb** [comment]
These are not years, there are that many pages in the pager. We set the pager to show only 10 pages. If people need to go deeper than that search is an option

**Comment by ndolter** [comment]
Validated in both languages that the issue is no longer occurring.
