### ISSUE TITLE
Links: On hover/on Focus links should have a visual change

### ISSUE THREAD

**Issue by mmiron-HC** [mmiron-HC/WST-RSAMS#92]
URL: https://hcdev.openplus.ca/en#wb-cont
User Agent: Chrome
Language:  English

Issue Description: When you hover (and On focus) over a link, there is no visual change.
looking at the code, it seems that both element states are overridden
![image](https://user-images.githubusercontent.com/65728700/131692711-2c6f4201-d7e2-48a6-aadf-acca5b21eb0a.png)

Steps to reproduce:
1. Using your mouse, hover over a link.

Expected results:
This is a [mandatory element of the Content and Information Architecture ](https://design.canada.ca/styles/colours.html)
Links should have a visual change when hovered or when in focus. (Usually there is a change of colour) 
see https://www.canada.ca/en/government/about/design-system.html for common look and feel.
![image](https://user-images.githubusercontent.com/65728700/131692357-ced98f4f-e128-4b8f-844c-d0f4ce45beca.png)

**Comment by ndolter** [comment]
Validated in both languages that when hovering there is visual change on the focus state.
